#! /usr/bin/env bash

set -o pipefail

filter_results() {
    sed -uE 's/legacyPackages.(aarch64-darwin|aarch64-linux|armv5tel-linux|armv6l-linux|armv7l-linux|i686-linux|mipsel-linux|powerpc64le-linux|riscv64-linux|x86_64-darwin|x86_64-linux).//g'
}

faketty nix --extra-experimental-features 'nix-command flakes' search --impure --expr '{ legacyPackages.${builtins.currentSystem} = import <nixpkgs> {};}' '' -- "$@" 2>/dev/null | filter_results
